/**
 * The ONE seam between this platform's own order/payment model and the
 * external provider that processes money. Every other service in this
 * module (OrdersService, the webhook handler, the billing queues)
 * depends on THIS interface and the `@Inject(PAYMENT_PROVIDER)` token —
 * never on a provider client directly or on a gateway HTTP shape.
 *
 * Implementations currently exist for Mercado Pago and PagBank. The
 * registry resolves the gateway recorded on each order/subscription;
 * the token remains the default Mercado Pago binding and the e2e seam.
 *
 * Two different vocabularies are deliberately mixed in this file, and
 * that split is intentional, not sloppy:
 *  - INPUT fields (`paymentMethod`, `billingPeriod`) use THIS platform's
 *    own vocabulary — the domain never has to know Mercado Pago calls a
 *    monthly cycle `frequency: 1, frequency_type: 'months'`.
 *  - OUTPUT `status` fields stay the PROVIDER's own vocabulary,
 *    UNTRANSLATED (`approved`, `rejected`, `authorized`, ...). The one
 *    place that interprets them is `classifyPayment`/
 *    `classifySubscription` below, which is implemented BY the provider
 *    — so provider vocabulary never leaks into the domain, and the
 *    domain's own `InternalPaymentEvent` stays a closed union.
 *
 * Every amount in this file is integer CENTS. Provider-specific decimal
 * conversions stay inside the corresponding adapter.
 */

export const PAYMENT_PROVIDER = Symbol('PAYMENT_PROVIDER');
export type PaymentProviderName = 'mercadopago' | 'pagbank';
export type PaymentMethod = 'pix' | 'boleto' | 'card';

/**
 * Thrown when the PROVIDER itself rejects a request as unprocessable in
 * a way the caller can act on (a payer the provider refuses, a
 * preapproval that no longer exists). Generic on purpose so
 * `OrdersService` never imports anything Mercado-Pago-shaped.
 */
export class PaymentProviderRequestError extends Error {
  constructor(
    message: string,
    readonly status: number,
    readonly providerCode: string | null = null,
  ) {
    super(message);
    this.name = 'PaymentProviderRequestError';
  }
}

/**
 * The platform's own outcome vocabulary, derived from a re-fetched
 * resource — never from a webhook's event name (Mercado Pago only ever
 * says `payment.created` / `payment.updated`; the truth is the
 * resource's own `status`). Kept as a closed union so the switch in
 * `PaymentsWebhookService.process` is exhaustively checked by the
 * compiler: an outcome this platform doesn't handle must be an explicit
 * `'Ignored'`, never a typo that silently falls through.
 */
export type InternalPaymentEvent =
  | 'PaymentConfirmed'
  | 'PaymentPending'
  | 'PaymentFailed'
  | 'PaymentCanceled'
  | 'PaymentRefunded'
  | 'PaymentChargeback'
  | 'SubscriptionSynced'
  | 'SubscriptionPastDue'
  | 'SubscriptionCanceled'
  | 'Ignored';

export interface PayerAddressInput {
  postalCode: string;
  addressLine: string;
  addressNumber: string;
  neighborhood: string;
  city: string;
  /** Two-letter Brazilian state code (UF). */
  state: string;
}

/**
 * The payer sent to Mercado Pago. Its e-mail is collected separately at
 * checkout and may differ from the GXHost account which owns the Order;
 * billing identity/address fields remain from that account's profile.
 * Mercado Pago has no mandatory customer resource for
 * either flow used here — a Pix charge identifies the payer inline
 * (`payer.email` + CPF) and a preapproval by `payer_email` alone — so
 * there is deliberately no `ensureCustomer` on this interface.
 */
export interface PayerInput {
  userId: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  /** Digits only. */
  cpf: string;
  address: PayerAddressInput;
}

interface ChargeInputBase {
  payer: PayerInput;
  /** Charged amount, integer cents. */
  amountCents: number;
  /** ISO 4217, e.g. 'BRL'. */
  currency: string;
  /** Human-readable line shown to the buyer (the plan's name). */
  description: string;
  /** `Order.externalReference` — server-generated, 192 bits, never accepted from the client. The ONLY key a Pix notification is matched back by. */
  externalReference: string;
  /**
   * Deterministic per-order key sent as Mercado Pago's own
   * `X-Idempotency-Key`, so a retried POST can never create a second
   * charge at the provider (their docs call this out explicitly for
   * both payments and refunds).
   */
  idempotencyKey: string;
}

/**
 * A one-off Pix charge (`POST /v1/payments`). Mercado Pago has NO
 * recurring Pix product — `/preapproval` is card-only — so every Pix
 * cycle is its own charge, generated by `BillingCycleProcessor` when the
 * period is about to turn over. That is exactly what `Subscription
 * .autoRenew = false` has always meant on this platform.
 */
export interface CreatePixChargeInput extends ChargeInputBase {
  /** `date_of_expiration`. Mercado Pago accepts 30 minutes to 30 days out. */
  expiresAt: Date;
}

/**
 * A boleto for ONE billing cycle. Like Pix, boleto is not an automatic
 * debit: BillingCycleProcessor creates a fresh charge for every renewal.
 */
export interface CreateBoletoChargeInput extends ChargeInputBase {
  expiresAt: Date;
}

/** A recurring card subscription (`POST /preapproval`) — Mercado Pago itself schedules and charges every cycle from here on. */
export interface CreateCardSubscriptionInput extends ChargeInputBase {
  billingPeriod: 'monthly' | 'quarterly' | 'semiannual' | 'annual';
  /** Where Mercado Pago sends the customer back after they authorize. UX only — authorization is confirmed by webhook, never by this redirect. */
  backUrl: string;
}

/**
 * The subset of a provider payment this platform persists (`payments`
 * table) — never card data, never anything beyond what `raw` (a
 * sanitized snapshot for admin diagnosis) already carries. `status` is
 * Mercado Pago's own vocabulary, untranslated (see this file's header).
 */
export interface GatewayPayment {
  id: string;
  status: string;
  statusDetail: string | null;
  /** The preapproval id this charge belongs to, when it is a recurring card charge. Null for a standalone Pix charge — those are matched by `externalReference` instead. */
  subscriptionExternalId: string | null;
  /** Echoed back by Mercado Pago from the request — the `Order.externalReference` this charge was created for. The ONLY way a Pix payment finds its order. */
  externalReference: string | null;
  amountCents: number | null;
  paidAmountCents: number | null;
  currency: string | null;
  paymentMethodId: string | null;
  paymentTypeId: string | null;
  installments: number | null;
  approvedAt: Date | null;
  raw: unknown;
}

/** A freshly created Pix charge — the QR is returned inline by `POST /v1/payments`, so there is no separate "fetch the QR" round trip. */
export interface PixCharge extends GatewayPayment {
  /** `point_of_interaction.transaction_data.qr_code` — the copy-and-paste Pix string. */
  qrCode: string;
  /** `point_of_interaction.transaction_data.qr_code_base64` — a PNG, base64, rendered inline by the client. */
  qrCodeBase64: string;
  expiresAt: Date | null;
}

/** A freshly created boleto. Providers may expose only a hosted ticket
 * URL (Mercado Pago) or also return a digitable line (PagBank). */
export interface BoletoCharge extends GatewayPayment {
  ticketUrl: string;
  digitableLine: string | null;
  expiresAt: Date | null;
}

/** `status` is the provider's own preapproval vocabulary (`pending`, `authorized`, `paused`, `cancelled`), untranslated. */
export interface GatewaySubscription {
  id: string;
  status: string;
  externalReference: string | null;
  nextDueDate: Date | null;
  /** `init_point` — the hosted page where the customer authorizes the card. Only present on creation. */
  initPoint: string | null;
  raw: unknown;
}

export interface RefundResult {
  id: string;
  status: string | null;
  amountCents: number | null;
}

/** Which Mercado Pago resource a notification is about — decides which endpoint the webhook service re-fetches from before acting. */
export type WebhookResourceKind = 'payment' | 'preapproval' | 'authorized_payment';

/**
 * A webhook notification, already verified authentic (the `x-signature`
 * HMAC checked BEFORE this is returned — see `parseWebhook`) and reduced
 * to "which resource changed".
 *
 * Deliberately carries NO outcome: Mercado Pago's notification says only
 * `payment.created`/`payment.updated`, and its body carries nothing but
 * an id. The outcome comes from re-fetching the resource and running it
 * through `classifyPayment`/`classifySubscription`.
 */
export interface ParsedWebhook {
  /** Mercado Pago's own notification id — the ONLY thing `payment_webhook_events.id` is keyed on for dedupe (at-least-once delivery, same PK-as-idempotency-key doctrine `Payment.id` already uses). */
  notificationId: string;
  /** `"<type>.<action>"` as received, kept for `payment_webhook_events.type` and audit logs. */
  rawEvent: string;
  /** `null` for a topic this platform doesn't handle — acknowledged and ignored. */
  resourceKind: WebhookResourceKind | null;
  resourceId: string | null;
}

/**
 * Framework-agnostic shape of an inbound webhook request — deliberately
 * NOT `FastifyRequest`, so this interface stays free of an HTTP-framework
 * dependency. The controller narrows the real request into this shape
 * before calling `parseWebhook`.
 */
export interface WebhookRequestInput {
  headers: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
  body: unknown;
  /** Original bytes required by PagBank's ECDSA webhook signature. */
  rawBody?: Buffer;
}

export interface PaymentProvider {
  /** Short, stable identifier written to `Order.provider`/`PaymentWebhookEvent.provider`. */
  readonly name: string;

  /** Lets the public checkout expose only gateways that can actually accept money in this deployment. */
  isConfigured?(): boolean;

  /** Payment methods this provider can accept in the current account/environment. */
  supportedPaymentMethods?(): PaymentMethod[];

  /** Creates the one-off Pix charge for ONE billing cycle. The QR comes back inline. */
  createPixCharge(input: CreatePixChargeInput): Promise<PixCharge>;
  /** Creates one boleto for ONE billing cycle. */
  createBoletoCharge(input: CreateBoletoChargeInput): Promise<BoletoCharge>;
  /** Creates the recurring card subscription. The returned `initPoint` is where the customer authorizes it; nothing is charged until they do. */
  createCardSubscription(input: CreateCardSubscriptionInput): Promise<GatewaySubscription>;

  /** Re-fetches ONE payment by its own id — the webhook body is never trusted as the financial source of truth. */
  getPayment(externalId: string): Promise<GatewayPayment>;
  /** Re-fetches a recurring charge (`GET /authorized_payments/{id}`) and normalizes it into the same `GatewayPayment` shape. */
  getAuthorizedPayment(externalId: string): Promise<GatewayPayment>;
  /** Re-fetches the preapproval (`GET /preapproval/{id}`). */
  getSubscription(externalId: string): Promise<GatewaySubscription>;
  /** Cancels at the provider — MUST succeed before this platform cancels its own `Subscription` row, or the customer keeps being charged with no record on our side of why. A subscription the provider no longer knows about counts as already cancelled. */
  cancelSubscription(externalId: string): Promise<void>;

  /** Omit `amountCents` for a full refund; provide it for a partial one. */
  refund(externalId: string, amountCents?: number): Promise<RefundResult>;

  /**
   * Turns a re-fetched payment into this platform's own outcome
   * vocabulary. Implemented by the provider so Mercado Pago's status
   * strings never leak into the domain.
   */
  classifyPayment(payment: GatewayPayment): InternalPaymentEvent;
  /** Same, for a re-fetched preapproval. An `authorized` preapproval is a SubscriptionSynced — never a payment: the customer authorized future charges, they have not paid yet. */
  classifySubscription(subscription: GatewaySubscription): InternalPaymentEvent;

  /**
   * Verifies the request's authenticity BEFORE anything in the body is
   * trusted, then reduces it to "which resource changed". Throws
   * (`UnauthorizedException`) when verification fails; never returns a
   * "maybe legitimate" result.
   *
   * Mercado Pago signs every notification with an HMAC-SHA256 over a
   * manifest built from the resource id, the `x-request-id` header and
   * the signature's own timestamp — so unlike a static shared token,
   * a captured request cannot be replayed against a different resource.
   * The caller's mandatory re-fetch-before-acting rule still stands on
   * top of it.
   */
  parseWebhook(req: WebhookRequestInput): ParsedWebhook | Promise<ParsedWebhook>;
}
