import { promises as fs } from 'node:fs';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { config, statePath } from './config';
import type { DesiredRoute, ProxyBackend } from './proxy-backend';

const execFileAsync = promisify(execFile);

/**
 * TCP-only, userspace proxy — nginx's `stream` module. Chosen over
 * nftables DNAT for the FIRST version deliberately (public-exposure
 * plan §1): simpler to operate and debug, no policy-routing setup on
 * the node side. Trade-off, documented and accepted for now: every
 * player's connection to the game server appears to come from THIS
 * gateway's own WireGuard IP, not the player's real one — see
 * docs/PUBLIC-EXPOSURE.md's "Limitação de IP real" section.
 *
 * One `server{}` block per route, in a file the real nginx.conf
 * `include`s from inside its `stream {}` block (deploy/gateway/nginx.conf).
 * `apply` REPLACES the whole file every time — never appends, never
 * diffs — which is what makes a route removed from `routes` actually
 * stop being proxied, and what makes running this twice with the same
 * input a no-op.
 */
export class NginxStreamBackend implements ProxyBackend {
  async apply(routes: DesiredRoute[]): Promise<void> {
    const rendered = this.render(routes);
    // Written to a temp path first, then renamed into place — an nginx
    // worker that re-reads this file mid-write (extremely unlikely, but
    // free to prevent) never sees a half-written config. Same directory
    // as the real target so the rename is atomic (same filesystem).
    const tmpPath = `${config.nginxConfPath}.tmp`;
    await fs.writeFile(tmpPath, rendered, 'utf8');
    await fs.rename(tmpPath, config.nginxConfPath);

    try {
      await execFileAsync('nginx', ['-t']);
    } catch (err) {
      throw new Error(`nginx -t failed after writing new config: ${(err as Error).message}`);
    }
    await execFileAsync('nginx', ['-s', 'reload']);

    // Persisted AFTER a successful reload — if either step above threw,
    // the state file still reflects the last config nginx actually
    // accepted, not the one we just failed to apply.
    await fs.writeFile(statePath, JSON.stringify(routes, null, 2), 'utf8');
  }

  async current(): Promise<DesiredRoute[]> {
    try {
      const raw = await fs.readFile(statePath, 'utf8');
      return JSON.parse(raw) as DesiredRoute[];
    } catch {
      return [];
    }
  }

  private render(routes: DesiredRoute[]): string {
    const header = `# Generated by @gxhost/gateway — DO NOT EDIT BY HAND.\n# Regenerated in full on every PUT /api/routes; any manual edit is lost on the next apply.\n\n`;
    const blocks = routes
      .map(
        (r) => `server {
    listen ${r.publicPort};
    proxy_pass ${r.targetIp}:${r.targetPort};
    proxy_timeout 10m;
    proxy_connect_timeout 5s;
    # serverId=${r.serverId}
}
`,
      )
      .join('\n');
    return header + blocks;
  }
}
