/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientRouteImport } from './routes/client'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as ClientAssistantRouteImport } from './routes/client.assistant'
import { Route as ClientBillingRouteImport } from './routes/client.billing'
import { Route as ClientPlanRouteImport } from './routes/client.plan'
import { Route as ClientSettingsRouteImport } from './routes/client.settings'
import { Route as ClientSupportRouteImport } from './routes/client.support'
import { Route as AdminNodesIndexRouteImport } from './routes/admin.nodes.index'
import { Route as AdminNodesNodeIdRouteImport } from './routes/admin.nodes.$nodeId'
import { Route as AdminServersIndexRouteImport } from './routes/admin.servers.index'
import { Route as AdminServersServerIdRouteImport } from './routes/admin.servers.$serverId'
import { Route as ClientServersIndexRouteImport } from './routes/client.servers.index'
import { Route as ClientServersServerIdRouteImport } from './routes/client.servers.$serverId'
import { Route as AdminServersServerIdIndexRouteImport } from './routes/admin.servers.$serverId.index'
import { Route as AdminServersServerIdActivityRouteImport } from './routes/admin.servers.$serverId.activity'
import { Route as AdminServersServerIdAddonsRouteImport } from './routes/admin.servers.$serverId.addons'
import { Route as AdminServersServerIdBackupsRouteImport } from './routes/admin.servers.$serverId.backups'
import { Route as AdminServersServerIdDatabasesRouteImport } from './routes/admin.servers.$serverId.databases'
import { Route as AdminServersServerIdFilesRouteImport } from './routes/admin.servers.$serverId.files'
import { Route as AdminServersServerIdSchedulesRouteImport } from './routes/admin.servers.$serverId.schedules'
import { Route as AdminServersServerIdSubusersRouteImport } from './routes/admin.servers.$serverId.subusers'
import { Route as AdminServersServerIdVariablesRouteImport } from './routes/admin.servers.$serverId.variables'
import { Route as ClientServersServerIdIndexRouteImport } from './routes/client.servers.$serverId.index'
import { Route as ClientServersServerIdActivityRouteImport } from './routes/client.servers.$serverId.activity'
import { Route as ClientServersServerIdAddonsRouteImport } from './routes/client.servers.$serverId.addons'
import { Route as ClientServersServerIdBackupsRouteImport } from './routes/client.servers.$serverId.backups'
import { Route as ClientServersServerIdDatabasesRouteImport } from './routes/client.servers.$serverId.databases'
import { Route as ClientServersServerIdFilesRouteImport } from './routes/client.servers.$serverId.files'
import { Route as ClientServersServerIdSchedulesRouteImport } from './routes/client.servers.$serverId.schedules'
import { Route as ClientServersServerIdSubusersRouteImport } from './routes/client.servers.$serverId.subusers'
import { Route as ClientServersServerIdVariablesRouteImport } from './routes/client.servers.$serverId.variables'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientAssistantRoute = ClientAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBillingRoute = ClientBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPlanRoute = ClientPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => ClientRoute,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientSupportRoute = ClientSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ClientRoute,
} as any)
const AdminNodesIndexRoute = AdminNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNodesNodeIdRoute = AdminNodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServersIndexRoute = AdminServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServersServerIdRoute = AdminServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => AdminRoute,
} as any)
const ClientServersIndexRoute = ClientServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientServersServerIdRoute = ClientServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => ClientRoute,
} as any)
const AdminServersServerIdIndexRoute =
  AdminServersServerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminServersServerIdRoute,
  } as any)
const AdminServersServerIdActivityRoute =
  AdminServersServerIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AdminServersServerIdRoute,
  } as any)
const AdminServersServerIdAddonsRoute =
  AdminServersServerIdAddonsRouteImport.update({
    id: '/addons',
    path: '/addons',
    getParentRoute: () => AdminServersServerIdRoute,
  } as any)
const AdminServersServerIdBackupsRoute =
  AdminServersServerIdBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => AdminServersServerIdRoute,
  } as any)
const AdminServersServerIdDatabasesRoute =
  AdminServersServerIdDatabasesRouteImport.update({
    id: '/databases',
    path: '/databases',
    getParentRoute: () => AdminServersServerIdRoute,
  } as any)
const AdminServersServerIdFilesRoute =
  AdminServersServerIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AdminServersServerIdRoute,
  } as any)
const AdminServersServerIdSchedulesRoute =
  AdminServersServerIdSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AdminServersServerIdRoute,
  } as any)
const AdminServersServerIdSubusersRoute =
  AdminServersServerIdSubusersRouteImport.update({
    id: '/subusers',
    path: '/subusers',
    getParentRoute: () => AdminServersServerIdRoute,
  } as any)
const AdminServersServerIdVariablesRoute =
  AdminServersServerIdVariablesRouteImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => AdminServersServerIdRoute,
  } as any)
const ClientServersServerIdIndexRoute =
  ClientServersServerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClientServersServerIdRoute,
  } as any)
const ClientServersServerIdActivityRoute =
  ClientServersServerIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ClientServersServerIdRoute,
  } as any)
const ClientServersServerIdAddonsRoute =
  ClientServersServerIdAddonsRouteImport.update({
    id: '/addons',
    path: '/addons',
    getParentRoute: () => ClientServersServerIdRoute,
  } as any)
const ClientServersServerIdBackupsRoute =
  ClientServersServerIdBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => ClientServersServerIdRoute,
  } as any)
const ClientServersServerIdDatabasesRoute =
  ClientServersServerIdDatabasesRouteImport.update({
    id: '/databases',
    path: '/databases',
    getParentRoute: () => ClientServersServerIdRoute,
  } as any)
const ClientServersServerIdFilesRoute =
  ClientServersServerIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => ClientServersServerIdRoute,
  } as any)
const ClientServersServerIdSchedulesRoute =
  ClientServersServerIdSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => ClientServersServerIdRoute,
  } as any)
const ClientServersServerIdSubusersRoute =
  ClientServersServerIdSubusersRouteImport.update({
    id: '/subusers',
    path: '/subusers',
    getParentRoute: () => ClientServersServerIdRoute,
  } as any)
const ClientServersServerIdVariablesRoute =
  ClientServersServerIdVariablesRouteImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => ClientServersServerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/assistant': typeof ClientAssistantRoute
  '/client/billing': typeof ClientBillingRoute
  '/client/plan': typeof ClientPlanRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/support': typeof ClientSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/nodes/$nodeId': typeof AdminNodesNodeIdRoute
  '/admin/servers/$serverId': typeof AdminServersServerIdRouteWithChildren
  '/client/servers/$serverId': typeof ClientServersServerIdRouteWithChildren
  '/admin/nodes/': typeof AdminNodesIndexRoute
  '/admin/servers/': typeof AdminServersIndexRoute
  '/client/servers/': typeof ClientServersIndexRoute
  '/admin/servers/$serverId/activity': typeof AdminServersServerIdActivityRoute
  '/admin/servers/$serverId/addons': typeof AdminServersServerIdAddonsRoute
  '/admin/servers/$serverId/backups': typeof AdminServersServerIdBackupsRoute
  '/admin/servers/$serverId/databases': typeof AdminServersServerIdDatabasesRoute
  '/admin/servers/$serverId/files': typeof AdminServersServerIdFilesRoute
  '/admin/servers/$serverId/schedules': typeof AdminServersServerIdSchedulesRoute
  '/admin/servers/$serverId/subusers': typeof AdminServersServerIdSubusersRoute
  '/admin/servers/$serverId/variables': typeof AdminServersServerIdVariablesRoute
  '/client/servers/$serverId/activity': typeof ClientServersServerIdActivityRoute
  '/client/servers/$serverId/addons': typeof ClientServersServerIdAddonsRoute
  '/client/servers/$serverId/backups': typeof ClientServersServerIdBackupsRoute
  '/client/servers/$serverId/databases': typeof ClientServersServerIdDatabasesRoute
  '/client/servers/$serverId/files': typeof ClientServersServerIdFilesRoute
  '/client/servers/$serverId/schedules': typeof ClientServersServerIdSchedulesRoute
  '/client/servers/$serverId/subusers': typeof ClientServersServerIdSubusersRoute
  '/client/servers/$serverId/variables': typeof ClientServersServerIdVariablesRoute
  '/admin/servers/$serverId/': typeof AdminServersServerIdIndexRoute
  '/client/servers/$serverId/': typeof ClientServersServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/assistant': typeof ClientAssistantRoute
  '/client/billing': typeof ClientBillingRoute
  '/client/plan': typeof ClientPlanRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/support': typeof ClientSupportRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/admin/nodes/$nodeId': typeof AdminNodesNodeIdRoute
  '/admin/nodes': typeof AdminNodesIndexRoute
  '/admin/servers': typeof AdminServersIndexRoute
  '/client/servers': typeof ClientServersIndexRoute
  '/admin/servers/$serverId/activity': typeof AdminServersServerIdActivityRoute
  '/admin/servers/$serverId/addons': typeof AdminServersServerIdAddonsRoute
  '/admin/servers/$serverId/backups': typeof AdminServersServerIdBackupsRoute
  '/admin/servers/$serverId/databases': typeof AdminServersServerIdDatabasesRoute
  '/admin/servers/$serverId/files': typeof AdminServersServerIdFilesRoute
  '/admin/servers/$serverId/schedules': typeof AdminServersServerIdSchedulesRoute
  '/admin/servers/$serverId/subusers': typeof AdminServersServerIdSubusersRoute
  '/admin/servers/$serverId/variables': typeof AdminServersServerIdVariablesRoute
  '/client/servers/$serverId/activity': typeof ClientServersServerIdActivityRoute
  '/client/servers/$serverId/addons': typeof ClientServersServerIdAddonsRoute
  '/client/servers/$serverId/backups': typeof ClientServersServerIdBackupsRoute
  '/client/servers/$serverId/databases': typeof ClientServersServerIdDatabasesRoute
  '/client/servers/$serverId/files': typeof ClientServersServerIdFilesRoute
  '/client/servers/$serverId/schedules': typeof ClientServersServerIdSchedulesRoute
  '/client/servers/$serverId/subusers': typeof ClientServersServerIdSubusersRoute
  '/client/servers/$serverId/variables': typeof ClientServersServerIdVariablesRoute
  '/admin/servers/$serverId': typeof AdminServersServerIdIndexRoute
  '/client/servers/$serverId': typeof ClientServersServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/assistant': typeof ClientAssistantRoute
  '/client/billing': typeof ClientBillingRoute
  '/client/plan': typeof ClientPlanRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/support': typeof ClientSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/nodes/$nodeId': typeof AdminNodesNodeIdRoute
  '/admin/servers/$serverId': typeof AdminServersServerIdRouteWithChildren
  '/client/servers/$serverId': typeof ClientServersServerIdRouteWithChildren
  '/admin/nodes/': typeof AdminNodesIndexRoute
  '/admin/servers/': typeof AdminServersIndexRoute
  '/client/servers/': typeof ClientServersIndexRoute
  '/admin/servers/$serverId/activity': typeof AdminServersServerIdActivityRoute
  '/admin/servers/$serverId/addons': typeof AdminServersServerIdAddonsRoute
  '/admin/servers/$serverId/backups': typeof AdminServersServerIdBackupsRoute
  '/admin/servers/$serverId/databases': typeof AdminServersServerIdDatabasesRoute
  '/admin/servers/$serverId/files': typeof AdminServersServerIdFilesRoute
  '/admin/servers/$serverId/schedules': typeof AdminServersServerIdSchedulesRoute
  '/admin/servers/$serverId/subusers': typeof AdminServersServerIdSubusersRoute
  '/admin/servers/$serverId/variables': typeof AdminServersServerIdVariablesRoute
  '/client/servers/$serverId/activity': typeof ClientServersServerIdActivityRoute
  '/client/servers/$serverId/addons': typeof ClientServersServerIdAddonsRoute
  '/client/servers/$serverId/backups': typeof ClientServersServerIdBackupsRoute
  '/client/servers/$serverId/databases': typeof ClientServersServerIdDatabasesRoute
  '/client/servers/$serverId/files': typeof ClientServersServerIdFilesRoute
  '/client/servers/$serverId/schedules': typeof ClientServersServerIdSchedulesRoute
  '/client/servers/$serverId/subusers': typeof ClientServersServerIdSubusersRoute
  '/client/servers/$serverId/variables': typeof ClientServersServerIdVariablesRoute
  '/admin/servers/$serverId/': typeof AdminServersServerIdIndexRoute
  '/client/servers/$serverId/': typeof ClientServersServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/locations'
    | '/admin/logs'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/system'
    | '/admin/templates'
    | '/admin/users'
    | '/client/assistant'
    | '/client/billing'
    | '/client/plan'
    | '/client/settings'
    | '/client/support'
    | '/admin/'
    | '/client/'
    | '/admin/nodes/$nodeId'
    | '/admin/servers/$serverId'
    | '/client/servers/$serverId'
    | '/admin/nodes/'
    | '/admin/servers/'
    | '/client/servers/'
    | '/admin/servers/$serverId/activity'
    | '/admin/servers/$serverId/addons'
    | '/admin/servers/$serverId/backups'
    | '/admin/servers/$serverId/databases'
    | '/admin/servers/$serverId/files'
    | '/admin/servers/$serverId/schedules'
    | '/admin/servers/$serverId/subusers'
    | '/admin/servers/$serverId/variables'
    | '/client/servers/$serverId/activity'
    | '/client/servers/$serverId/addons'
    | '/client/servers/$serverId/backups'
    | '/client/servers/$serverId/databases'
    | '/client/servers/$serverId/files'
    | '/client/servers/$serverId/schedules'
    | '/client/servers/$serverId/subusers'
    | '/client/servers/$serverId/variables'
    | '/admin/servers/$serverId/'
    | '/client/servers/$serverId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/locations'
    | '/admin/logs'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/system'
    | '/admin/templates'
    | '/admin/users'
    | '/client/assistant'
    | '/client/billing'
    | '/client/plan'
    | '/client/settings'
    | '/client/support'
    | '/admin'
    | '/client'
    | '/admin/nodes/$nodeId'
    | '/admin/nodes'
    | '/admin/servers'
    | '/client/servers'
    | '/admin/servers/$serverId/activity'
    | '/admin/servers/$serverId/addons'
    | '/admin/servers/$serverId/backups'
    | '/admin/servers/$serverId/databases'
    | '/admin/servers/$serverId/files'
    | '/admin/servers/$serverId/schedules'
    | '/admin/servers/$serverId/subusers'
    | '/admin/servers/$serverId/variables'
    | '/client/servers/$serverId/activity'
    | '/client/servers/$serverId/addons'
    | '/client/servers/$serverId/backups'
    | '/client/servers/$serverId/databases'
    | '/client/servers/$serverId/files'
    | '/client/servers/$serverId/schedules'
    | '/client/servers/$serverId/subusers'
    | '/client/servers/$serverId/variables'
    | '/admin/servers/$serverId'
    | '/client/servers/$serverId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/locations'
    | '/admin/logs'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/system'
    | '/admin/templates'
    | '/admin/users'
    | '/client/assistant'
    | '/client/billing'
    | '/client/plan'
    | '/client/settings'
    | '/client/support'
    | '/admin/'
    | '/client/'
    | '/admin/nodes/$nodeId'
    | '/admin/servers/$serverId'
    | '/client/servers/$serverId'
    | '/admin/nodes/'
    | '/admin/servers/'
    | '/client/servers/'
    | '/admin/servers/$serverId/activity'
    | '/admin/servers/$serverId/addons'
    | '/admin/servers/$serverId/backups'
    | '/admin/servers/$serverId/databases'
    | '/admin/servers/$serverId/files'
    | '/admin/servers/$serverId/schedules'
    | '/admin/servers/$serverId/subusers'
    | '/admin/servers/$serverId/variables'
    | '/client/servers/$serverId/activity'
    | '/client/servers/$serverId/addons'
    | '/client/servers/$serverId/backups'
    | '/client/servers/$serverId/databases'
    | '/client/servers/$serverId/files'
    | '/client/servers/$serverId/schedules'
    | '/client/servers/$serverId/subusers'
    | '/client/servers/$serverId/variables'
    | '/admin/servers/$serverId/'
    | '/client/servers/$serverId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/assistant': {
      id: '/client/assistant'
      path: '/assistant'
      fullPath: '/client/assistant'
      preLoaderRoute: typeof ClientAssistantRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/billing': {
      id: '/client/billing'
      path: '/billing'
      fullPath: '/client/billing'
      preLoaderRoute: typeof ClientBillingRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/plan': {
      id: '/client/plan'
      path: '/plan'
      fullPath: '/client/plan'
      preLoaderRoute: typeof ClientPlanRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/settings': {
      id: '/client/settings'
      path: '/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/support': {
      id: '/client/support'
      path: '/support'
      fullPath: '/client/support'
      preLoaderRoute: typeof ClientSupportRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/nodes/': {
      id: '/admin/nodes/'
      path: '/nodes'
      fullPath: '/admin/nodes/'
      preLoaderRoute: typeof AdminNodesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nodes/$nodeId': {
      id: '/admin/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/admin/nodes/$nodeId'
      preLoaderRoute: typeof AdminNodesNodeIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servers/': {
      id: '/admin/servers/'
      path: '/servers'
      fullPath: '/admin/servers/'
      preLoaderRoute: typeof AdminServersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servers/$serverId': {
      id: '/admin/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/admin/servers/$serverId'
      preLoaderRoute: typeof AdminServersServerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/servers/': {
      id: '/client/servers/'
      path: '/servers'
      fullPath: '/client/servers/'
      preLoaderRoute: typeof ClientServersIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/servers/$serverId': {
      id: '/client/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/client/servers/$serverId'
      preLoaderRoute: typeof ClientServersServerIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/servers/$serverId/': {
      id: '/admin/servers/$serverId/'
      path: '/'
      fullPath: '/admin/servers/$serverId/'
      preLoaderRoute: typeof AdminServersServerIdIndexRouteImport
      parentRoute: typeof AdminServersServerIdRoute
    }
    '/admin/servers/$serverId/activity': {
      id: '/admin/servers/$serverId/activity'
      path: '/activity'
      fullPath: '/admin/servers/$serverId/activity'
      preLoaderRoute: typeof AdminServersServerIdActivityRouteImport
      parentRoute: typeof AdminServersServerIdRoute
    }
    '/admin/servers/$serverId/addons': {
      id: '/admin/servers/$serverId/addons'
      path: '/addons'
      fullPath: '/admin/servers/$serverId/addons'
      preLoaderRoute: typeof AdminServersServerIdAddonsRouteImport
      parentRoute: typeof AdminServersServerIdRoute
    }
    '/admin/servers/$serverId/backups': {
      id: '/admin/servers/$serverId/backups'
      path: '/backups'
      fullPath: '/admin/servers/$serverId/backups'
      preLoaderRoute: typeof AdminServersServerIdBackupsRouteImport
      parentRoute: typeof AdminServersServerIdRoute
    }
    '/admin/servers/$serverId/databases': {
      id: '/admin/servers/$serverId/databases'
      path: '/databases'
      fullPath: '/admin/servers/$serverId/databases'
      preLoaderRoute: typeof AdminServersServerIdDatabasesRouteImport
      parentRoute: typeof AdminServersServerIdRoute
    }
    '/admin/servers/$serverId/files': {
      id: '/admin/servers/$serverId/files'
      path: '/files'
      fullPath: '/admin/servers/$serverId/files'
      preLoaderRoute: typeof AdminServersServerIdFilesRouteImport
      parentRoute: typeof AdminServersServerIdRoute
    }
    '/admin/servers/$serverId/schedules': {
      id: '/admin/servers/$serverId/schedules'
      path: '/schedules'
      fullPath: '/admin/servers/$serverId/schedules'
      preLoaderRoute: typeof AdminServersServerIdSchedulesRouteImport
      parentRoute: typeof AdminServersServerIdRoute
    }
    '/admin/servers/$serverId/subusers': {
      id: '/admin/servers/$serverId/subusers'
      path: '/subusers'
      fullPath: '/admin/servers/$serverId/subusers'
      preLoaderRoute: typeof AdminServersServerIdSubusersRouteImport
      parentRoute: typeof AdminServersServerIdRoute
    }
    '/admin/servers/$serverId/variables': {
      id: '/admin/servers/$serverId/variables'
      path: '/variables'
      fullPath: '/admin/servers/$serverId/variables'
      preLoaderRoute: typeof AdminServersServerIdVariablesRouteImport
      parentRoute: typeof AdminServersServerIdRoute
    }
    '/client/servers/$serverId/': {
      id: '/client/servers/$serverId/'
      path: '/'
      fullPath: '/client/servers/$serverId/'
      preLoaderRoute: typeof ClientServersServerIdIndexRouteImport
      parentRoute: typeof ClientServersServerIdRoute
    }
    '/client/servers/$serverId/activity': {
      id: '/client/servers/$serverId/activity'
      path: '/activity'
      fullPath: '/client/servers/$serverId/activity'
      preLoaderRoute: typeof ClientServersServerIdActivityRouteImport
      parentRoute: typeof ClientServersServerIdRoute
    }
    '/client/servers/$serverId/addons': {
      id: '/client/servers/$serverId/addons'
      path: '/addons'
      fullPath: '/client/servers/$serverId/addons'
      preLoaderRoute: typeof ClientServersServerIdAddonsRouteImport
      parentRoute: typeof ClientServersServerIdRoute
    }
    '/client/servers/$serverId/backups': {
      id: '/client/servers/$serverId/backups'
      path: '/backups'
      fullPath: '/client/servers/$serverId/backups'
      preLoaderRoute: typeof ClientServersServerIdBackupsRouteImport
      parentRoute: typeof ClientServersServerIdRoute
    }
    '/client/servers/$serverId/databases': {
      id: '/client/servers/$serverId/databases'
      path: '/databases'
      fullPath: '/client/servers/$serverId/databases'
      preLoaderRoute: typeof ClientServersServerIdDatabasesRouteImport
      parentRoute: typeof ClientServersServerIdRoute
    }
    '/client/servers/$serverId/files': {
      id: '/client/servers/$serverId/files'
      path: '/files'
      fullPath: '/client/servers/$serverId/files'
      preLoaderRoute: typeof ClientServersServerIdFilesRouteImport
      parentRoute: typeof ClientServersServerIdRoute
    }
    '/client/servers/$serverId/schedules': {
      id: '/client/servers/$serverId/schedules'
      path: '/schedules'
      fullPath: '/client/servers/$serverId/schedules'
      preLoaderRoute: typeof ClientServersServerIdSchedulesRouteImport
      parentRoute: typeof ClientServersServerIdRoute
    }
    '/client/servers/$serverId/subusers': {
      id: '/client/servers/$serverId/subusers'
      path: '/subusers'
      fullPath: '/client/servers/$serverId/subusers'
      preLoaderRoute: typeof ClientServersServerIdSubusersRouteImport
      parentRoute: typeof ClientServersServerIdRoute
    }
    '/client/servers/$serverId/variables': {
      id: '/client/servers/$serverId/variables'
      path: '/variables'
      fullPath: '/client/servers/$serverId/variables'
      preLoaderRoute: typeof ClientServersServerIdVariablesRouteImport
      parentRoute: typeof ClientServersServerIdRoute
    }
  }
}

interface AdminServersServerIdRouteChildren {
  AdminServersServerIdActivityRoute: typeof AdminServersServerIdActivityRoute
  AdminServersServerIdAddonsRoute: typeof AdminServersServerIdAddonsRoute
  AdminServersServerIdBackupsRoute: typeof AdminServersServerIdBackupsRoute
  AdminServersServerIdDatabasesRoute: typeof AdminServersServerIdDatabasesRoute
  AdminServersServerIdFilesRoute: typeof AdminServersServerIdFilesRoute
  AdminServersServerIdSchedulesRoute: typeof AdminServersServerIdSchedulesRoute
  AdminServersServerIdSubusersRoute: typeof AdminServersServerIdSubusersRoute
  AdminServersServerIdVariablesRoute: typeof AdminServersServerIdVariablesRoute
  AdminServersServerIdIndexRoute: typeof AdminServersServerIdIndexRoute
}

const AdminServersServerIdRouteChildren: AdminServersServerIdRouteChildren = {
  AdminServersServerIdActivityRoute: AdminServersServerIdActivityRoute,
  AdminServersServerIdAddonsRoute: AdminServersServerIdAddonsRoute,
  AdminServersServerIdBackupsRoute: AdminServersServerIdBackupsRoute,
  AdminServersServerIdDatabasesRoute: AdminServersServerIdDatabasesRoute,
  AdminServersServerIdFilesRoute: AdminServersServerIdFilesRoute,
  AdminServersServerIdSchedulesRoute: AdminServersServerIdSchedulesRoute,
  AdminServersServerIdSubusersRoute: AdminServersServerIdSubusersRoute,
  AdminServersServerIdVariablesRoute: AdminServersServerIdVariablesRoute,
  AdminServersServerIdIndexRoute: AdminServersServerIdIndexRoute,
}

const AdminServersServerIdRouteWithChildren =
  AdminServersServerIdRoute._addFileChildren(AdminServersServerIdRouteChildren)

interface AdminRouteChildren {
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminNodesNodeIdRoute: typeof AdminNodesNodeIdRoute
  AdminServersServerIdRoute: typeof AdminServersServerIdRouteWithChildren
  AdminNodesIndexRoute: typeof AdminNodesIndexRoute
  AdminServersIndexRoute: typeof AdminServersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLocationsRoute: AdminLocationsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminNodesNodeIdRoute: AdminNodesNodeIdRoute,
  AdminServersServerIdRoute: AdminServersServerIdRouteWithChildren,
  AdminNodesIndexRoute: AdminNodesIndexRoute,
  AdminServersIndexRoute: AdminServersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientServersServerIdRouteChildren {
  ClientServersServerIdActivityRoute: typeof ClientServersServerIdActivityRoute
  ClientServersServerIdAddonsRoute: typeof ClientServersServerIdAddonsRoute
  ClientServersServerIdBackupsRoute: typeof ClientServersServerIdBackupsRoute
  ClientServersServerIdDatabasesRoute: typeof ClientServersServerIdDatabasesRoute
  ClientServersServerIdFilesRoute: typeof ClientServersServerIdFilesRoute
  ClientServersServerIdSchedulesRoute: typeof ClientServersServerIdSchedulesRoute
  ClientServersServerIdSubusersRoute: typeof ClientServersServerIdSubusersRoute
  ClientServersServerIdVariablesRoute: typeof ClientServersServerIdVariablesRoute
  ClientServersServerIdIndexRoute: typeof ClientServersServerIdIndexRoute
}

const ClientServersServerIdRouteChildren: ClientServersServerIdRouteChildren = {
  ClientServersServerIdActivityRoute: ClientServersServerIdActivityRoute,
  ClientServersServerIdAddonsRoute: ClientServersServerIdAddonsRoute,
  ClientServersServerIdBackupsRoute: ClientServersServerIdBackupsRoute,
  ClientServersServerIdDatabasesRoute: ClientServersServerIdDatabasesRoute,
  ClientServersServerIdFilesRoute: ClientServersServerIdFilesRoute,
  ClientServersServerIdSchedulesRoute: ClientServersServerIdSchedulesRoute,
  ClientServersServerIdSubusersRoute: ClientServersServerIdSubusersRoute,
  ClientServersServerIdVariablesRoute: ClientServersServerIdVariablesRoute,
  ClientServersServerIdIndexRoute: ClientServersServerIdIndexRoute,
}

const ClientServersServerIdRouteWithChildren =
  ClientServersServerIdRoute._addFileChildren(
    ClientServersServerIdRouteChildren,
  )

interface ClientRouteChildren {
  ClientAssistantRoute: typeof ClientAssistantRoute
  ClientBillingRoute: typeof ClientBillingRoute
  ClientPlanRoute: typeof ClientPlanRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientSupportRoute: typeof ClientSupportRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientServersServerIdRoute: typeof ClientServersServerIdRouteWithChildren
  ClientServersIndexRoute: typeof ClientServersIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientAssistantRoute: ClientAssistantRoute,
  ClientBillingRoute: ClientBillingRoute,
  ClientPlanRoute: ClientPlanRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientSupportRoute: ClientSupportRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientServersServerIdRoute: ClientServersServerIdRouteWithChildren,
  ClientServersIndexRoute: ClientServersIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
