/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminNodesRouteImport } from './routes/admin.nodes'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminServersRouteImport } from './routes/admin.servers'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as ServersServerIdRouteImport } from './routes/servers.$serverId'
import { Route as ServersServerIdIndexRouteImport } from './routes/servers.$serverId.index'
import { Route as ServersServerIdActivityRouteImport } from './routes/servers.$serverId.activity'
import { Route as ServersServerIdBackupsRouteImport } from './routes/servers.$serverId.backups'
import { Route as ServersServerIdDatabasesRouteImport } from './routes/servers.$serverId.databases'
import { Route as ServersServerIdFilesRouteImport } from './routes/servers.$serverId.files'
import { Route as ServersServerIdSchedulesRouteImport } from './routes/servers.$serverId.schedules'
import { Route as ServersServerIdSubusersRouteImport } from './routes/servers.$serverId.subusers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNodesRoute = AdminNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServersRoute = AdminServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdIndexRoute = ServersServerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServersServerIdRoute,
} as any)
const ServersServerIdActivityRoute = ServersServerIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ServersServerIdRoute,
} as any)
const ServersServerIdBackupsRoute = ServersServerIdBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => ServersServerIdRoute,
} as any)
const ServersServerIdDatabasesRoute =
  ServersServerIdDatabasesRouteImport.update({
    id: '/databases',
    path: '/databases',
    getParentRoute: () => ServersServerIdRoute,
  } as any)
const ServersServerIdFilesRoute = ServersServerIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ServersServerIdRoute,
} as any)
const ServersServerIdSchedulesRoute =
  ServersServerIdSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => ServersServerIdRoute,
  } as any)
const ServersServerIdSubusersRoute = ServersServerIdSubusersRouteImport.update({
  id: '/subusers',
  path: '/subusers',
  getParentRoute: () => ServersServerIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/nodes': typeof AdminNodesRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/servers': typeof AdminServersRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/servers/$serverId/activity': typeof ServersServerIdActivityRoute
  '/servers/$serverId/backups': typeof ServersServerIdBackupsRoute
  '/servers/$serverId/databases': typeof ServersServerIdDatabasesRoute
  '/servers/$serverId/files': typeof ServersServerIdFilesRoute
  '/servers/$serverId/schedules': typeof ServersServerIdSchedulesRoute
  '/servers/$serverId/subusers': typeof ServersServerIdSubusersRoute
  '/servers/$serverId/': typeof ServersServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/nodes': typeof AdminNodesRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/servers': typeof AdminServersRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin': typeof AdminIndexRoute
  '/servers/$serverId/activity': typeof ServersServerIdActivityRoute
  '/servers/$serverId/backups': typeof ServersServerIdBackupsRoute
  '/servers/$serverId/databases': typeof ServersServerIdDatabasesRoute
  '/servers/$serverId/files': typeof ServersServerIdFilesRoute
  '/servers/$serverId/schedules': typeof ServersServerIdSchedulesRoute
  '/servers/$serverId/subusers': typeof ServersServerIdSubusersRoute
  '/servers/$serverId': typeof ServersServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/nodes': typeof AdminNodesRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/servers': typeof AdminServersRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/servers/$serverId/activity': typeof ServersServerIdActivityRoute
  '/servers/$serverId/backups': typeof ServersServerIdBackupsRoute
  '/servers/$serverId/databases': typeof ServersServerIdDatabasesRoute
  '/servers/$serverId/files': typeof ServersServerIdFilesRoute
  '/servers/$serverId/schedules': typeof ServersServerIdSchedulesRoute
  '/servers/$serverId/subusers': typeof ServersServerIdSubusersRoute
  '/servers/$serverId/': typeof ServersServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/nodes'
    | '/admin/plans'
    | '/admin/servers'
    | '/admin/templates'
    | '/servers/$serverId'
    | '/admin/'
    | '/servers/$serverId/activity'
    | '/servers/$serverId/backups'
    | '/servers/$serverId/databases'
    | '/servers/$serverId/files'
    | '/servers/$serverId/schedules'
    | '/servers/$serverId/subusers'
    | '/servers/$serverId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/nodes'
    | '/admin/plans'
    | '/admin/servers'
    | '/admin/templates'
    | '/admin'
    | '/servers/$serverId/activity'
    | '/servers/$serverId/backups'
    | '/servers/$serverId/databases'
    | '/servers/$serverId/files'
    | '/servers/$serverId/schedules'
    | '/servers/$serverId/subusers'
    | '/servers/$serverId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/nodes'
    | '/admin/plans'
    | '/admin/servers'
    | '/admin/templates'
    | '/servers/$serverId'
    | '/admin/'
    | '/servers/$serverId/activity'
    | '/servers/$serverId/backups'
    | '/servers/$serverId/databases'
    | '/servers/$serverId/files'
    | '/servers/$serverId/schedules'
    | '/servers/$serverId/subusers'
    | '/servers/$serverId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ServersServerIdRoute: typeof ServersServerIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nodes': {
      id: '/admin/nodes'
      path: '/nodes'
      fullPath: '/admin/nodes'
      preLoaderRoute: typeof AdminNodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servers': {
      id: '/admin/servers'
      path: '/servers'
      fullPath: '/admin/servers'
      preLoaderRoute: typeof AdminServersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId/': {
      id: '/servers/$serverId/'
      path: '/'
      fullPath: '/servers/$serverId/'
      preLoaderRoute: typeof ServersServerIdIndexRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/servers/$serverId/activity': {
      id: '/servers/$serverId/activity'
      path: '/activity'
      fullPath: '/servers/$serverId/activity'
      preLoaderRoute: typeof ServersServerIdActivityRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/servers/$serverId/backups': {
      id: '/servers/$serverId/backups'
      path: '/backups'
      fullPath: '/servers/$serverId/backups'
      preLoaderRoute: typeof ServersServerIdBackupsRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/servers/$serverId/databases': {
      id: '/servers/$serverId/databases'
      path: '/databases'
      fullPath: '/servers/$serverId/databases'
      preLoaderRoute: typeof ServersServerIdDatabasesRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/servers/$serverId/files': {
      id: '/servers/$serverId/files'
      path: '/files'
      fullPath: '/servers/$serverId/files'
      preLoaderRoute: typeof ServersServerIdFilesRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/servers/$serverId/schedules': {
      id: '/servers/$serverId/schedules'
      path: '/schedules'
      fullPath: '/servers/$serverId/schedules'
      preLoaderRoute: typeof ServersServerIdSchedulesRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/servers/$serverId/subusers': {
      id: '/servers/$serverId/subusers'
      path: '/subusers'
      fullPath: '/servers/$serverId/subusers'
      preLoaderRoute: typeof ServersServerIdSubusersRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminNodesRoute: typeof AdminNodesRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminServersRoute: typeof AdminServersRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminNodesRoute: AdminNodesRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminServersRoute: AdminServersRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServersServerIdRouteChildren {
  ServersServerIdActivityRoute: typeof ServersServerIdActivityRoute
  ServersServerIdBackupsRoute: typeof ServersServerIdBackupsRoute
  ServersServerIdDatabasesRoute: typeof ServersServerIdDatabasesRoute
  ServersServerIdFilesRoute: typeof ServersServerIdFilesRoute
  ServersServerIdSchedulesRoute: typeof ServersServerIdSchedulesRoute
  ServersServerIdSubusersRoute: typeof ServersServerIdSubusersRoute
  ServersServerIdIndexRoute: typeof ServersServerIdIndexRoute
}

const ServersServerIdRouteChildren: ServersServerIdRouteChildren = {
  ServersServerIdActivityRoute: ServersServerIdActivityRoute,
  ServersServerIdBackupsRoute: ServersServerIdBackupsRoute,
  ServersServerIdDatabasesRoute: ServersServerIdDatabasesRoute,
  ServersServerIdFilesRoute: ServersServerIdFilesRoute,
  ServersServerIdSchedulesRoute: ServersServerIdSchedulesRoute,
  ServersServerIdSubusersRoute: ServersServerIdSubusersRoute,
  ServersServerIdIndexRoute: ServersServerIdIndexRoute,
}

const ServersServerIdRouteWithChildren = ServersServerIdRoute._addFileChildren(
  ServersServerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ServersServerIdRoute: ServersServerIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
